[package]
name = "kvm"
version = "0.1.0"
authors = ["Jeremy Rodi <me@medcat.me>"]

[dependencies]
nix = "0.10"
error-chain = "0.11.0"
kvm-sys = { path = "../kvm-sys", version = "0.1.0" }
byteorder = "1"
mio = "0.6"
tokio = "0.1"
bitflags = "1"
memmap = "0.7"
